version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      octokit:
        patterns:
          - "@octokit/*"
      jest:
        patterns:
          - "jest"
          - "ts-jest"
          - "@types/jest"
          - "jest-environment-jsdom"
      obsidian-types:
        patterns:
          - "obsidian"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
